server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: beaver-gateway-${ENV:local}

  cloud:
    gateway:
      routes:
        - id: beaver-identity-auth
          uri: ${beaver.identity.url}
          predicates:
            - Path=/identity/auth/**
          filters:
            # TODO: LoggingFilter
            - name: ContextEnrichmentFilter

        - id: beaver-identity
          uri: ${beaver.identity.url}
          predicates:
            - Path=/identity/**
          filters:
            # TODO: LoggingFilter
            - name: AuthenticationFilter
            - name: ContextEnrichmentFilter

logging:
  level:
    com.beaver.core: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.handler.FilteringWebHandler: WARN

jwt:
  secret: ${JWT_SECRET}
  accessTokenValidity: ${JWT_ACCESS_VALIDITY}
  refreshTokenValidity: ${JWT_REFRESH_VALIDITY}
  authDisabled: false

gateway:
  secret: ${GATEWAY_SECRET}..+

# Downstream Services
beaver:
  identity:
    url: ${BEAVER_IDENTITY_URL:http://localhost:8081}
